[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[100]
type=endpoint
context=whatsapp-viber-gateway
disallow=all
allow=ulaw,alaw,g722
auth=100-auth
aors=100

[100-auth]
type=auth
auth_type=userpass
username=100
password=YOUR_PASSWORD_HERE  ; <--- Set your own password

[100]
type=aor
max_contacts=5

[200]
type=endpoint
context=whatsapp-viber-gateway
disallow=all
allow=ulaw,alaw,g722
auth=200-auth
aors=200

[200-auth]
type=auth
auth_type=userpass
username=200
password=YOUR_PASSWORD_HERE  ; <--- Set your Windows VM password

[200]
type=aor
max_contacts=5
